volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: sharkface34/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media

  frontend:
    image: sharkface34/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    image: sharkface34/foodgram_nginx:latest
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media
    ports:
      - 7000:80
